apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.selector }}"
spec:
  replicas: "{{ .Values.replica }}"
  selector:
    matchLabels:
      app: "{{ .Values.selector }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.selector }}"
    spec:
      containers:
      - name: "{{ .Values.name }}"
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
        - containerPort: "{{ .Values.containersportNumber }}"