apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.selector }}"
  ports:
  - port: 80
    targetPort: "{{ .Values.containersportNumber }}"